name = "backend"
compatibility_date = "2023-12-01"

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmFlNDY4ZTgtNmUyYy00ODAzLWE5ZGMtNWRhYjFkNmRmMzdlIiwidGVuYW50X2lkIjoiMzUzNjg1MzBkOWExM2M5ZWFiMGZiZWUwZDIzMTg0Mzk2ZTVkZGRjZjI3OTg1MzRkODRhNGFjZmVkZmM0NjMzZiIsImludGVybmFsX3NlY3JldCI6IjE1MmJmYTEzLWUyMmYtNDFhMC04MzkwLTMyMTA0YmVkYzMyZiJ9.LGuj85flWGZJsu2Jq8nDJOmcd8Qi-3eYyDSSvBKts6M"
JWT_SECRET="c3VjayBteSBkaWNrIGFuZCB0aGVuIGkgd2lsbCBmdWNrIHlvdXIgcHVzc3kgeW91IGJpdGNo"

